# Setup
title:               My Silly Blog
tagline:             'bebebea.github.io'
description:         'A silly blog where I write silly stuff.'
url:                 https://bebebea.github.io
domain:              bebebea.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
