# Setup
title:               My Silly Blog
tagline:             'Sometimes I like writing stuff down.'
description:         'Hi! Welcome!'
url:                 https://bebebea.github.io/
domain:              bebebea.github.io
baseurl:             'https://bebebea.github.io/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
